/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiskor;

/**
 *
 * @author daffa
 */
public class Scoreboard extends javax.swing.JFrame {

    /**
     * Creates new form Scoreboard
     */
    public Scoreboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scoreB = new javax.swing.JLabel();
        scoreA = new javax.swing.JLabel();
        poinA1 = new javax.swing.JButton();
        poinA2 = new javax.swing.JButton();
        poinA3 = new javax.swing.JButton();
        poinB1 = new javax.swing.JButton();
        poinB2 = new javax.swing.JButton();
        poinB3 = new javax.swing.JButton();
        labelSkor = new javax.swing.JLabel();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("TIM A");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("TIM B");

        scoreB.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        scoreB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreB.setText("0");

        scoreA.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        scoreA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreA.setText("0");

        poinA1.setText("1 Poin");
        poinA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poinA1ActionPerformed(evt);
            }
        });

        poinA2.setText("2 Poin");
        poinA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poinA2ActionPerformed(evt);
            }
        });

        poinA3.setText("3 Poin");
        poinA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poinA3ActionPerformed(evt);
            }
        });

        poinB1.setText("1 Poin");
        poinB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poinB1ActionPerformed(evt);
            }
        });

        poinB2.setText("2 Poin");
        poinB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poinB2ActionPerformed(evt);
            }
        });

        poinB3.setText("3 Poin");
        poinB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poinB3ActionPerformed(evt);
            }
        });

        labelSkor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelSkor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSkor.setText("IMBANG");

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(scoreA, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(poinA3)
                            .addComponent(poinA2)
                            .addComponent(poinA1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scoreB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(poinB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poinB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poinB1))
                        .addGap(9, 9, 9)))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelSkor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreA, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreB, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(poinA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poinA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poinA3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(poinB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poinB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poinB3)))
                .addGap(26, 26, 26)
                .addComponent(labelSkor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reset)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poinA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poinA1ActionPerformed
        scoreA.setText(String.valueOf(Integer.parseInt(scoreA.getText()) + 1));
        cekSkor();
    }//GEN-LAST:event_poinA1ActionPerformed

    private void poinA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poinA2ActionPerformed
        scoreA.setText(String.valueOf(Integer.parseInt(scoreA.getText()) + 2));
        cekSkor();
    }//GEN-LAST:event_poinA2ActionPerformed

    private void poinA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poinA3ActionPerformed
        scoreA.setText(String.valueOf(Integer.parseInt(scoreA.getText()) + 3));
        cekSkor();
    }//GEN-LAST:event_poinA3ActionPerformed

    private void poinB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poinB1ActionPerformed
        scoreB.setText(String.valueOf(Integer.parseInt(scoreB.getText()) + 1));
        cekSkor();
    }//GEN-LAST:event_poinB1ActionPerformed

    private void poinB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poinB2ActionPerformed
        scoreB.setText(String.valueOf(Integer.parseInt(scoreB.getText()) + 2));
        cekSkor();
    }//GEN-LAST:event_poinB2ActionPerformed

    private void poinB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poinB3ActionPerformed
        scoreB.setText(String.valueOf(Integer.parseInt(scoreB.getText()) + 3));
        cekSkor();
    }//GEN-LAST:event_poinB3ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        scoreA.setText("0");
        scoreB.setText("0");
        cekSkor();
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scoreboard().setVisible(true);
            }
        });
    }
    
    public void cekSkor(){
        int skorA = Integer.parseInt(scoreA.getText());
        int skorB = Integer.parseInt(scoreB.getText());
        
        if (skorA > skorB) {
            labelSkor.setText("Tim A Unggul");
        } else if (skorB > skorA) {
            labelSkor.setText("Tim B Unggul");
        } else {
            labelSkor.setText("IMBANG");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelSkor;
    private javax.swing.JButton poinA1;
    private javax.swing.JButton poinA2;
    private javax.swing.JButton poinA3;
    private javax.swing.JButton poinB1;
    private javax.swing.JButton poinB2;
    private javax.swing.JButton poinB3;
    private javax.swing.JButton reset;
    private javax.swing.JLabel scoreA;
    private javax.swing.JLabel scoreB;
    // End of variables declaration//GEN-END:variables
}
