/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manajemenrumahsakit;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import backend.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class AdminMenuWardList extends javax.swing.JFrame {
    private DefaultTableModel model;

    /**
     * Creates new form MenuWard
     */
    public AdminMenuWardList() {
        initComponents();
        model = new DefaultTableModel();
        this.tblWardList.setModel(model);
        model.addColumn("Ward Code");
        model.addColumn("Ward Name");
        this.setLocationRelativeTo(null);
        dataToTable();
    }
    
    private void dataToTable() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        for (Kamar kamar : new Kamar().getAll()) {
            Object[] o = new Object[2];
            o[0] = String.valueOf(kamar.getKdKamar());
            o[1] = kamar.getNamaKamar();
            model.addRow(o);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labekManage = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        laeblDashboard = new javax.swing.JLabel();
        labelDoctor = new javax.swing.JLabel();
        labelWard = new javax.swing.JLabel();
        labelPatient = new javax.swing.JLabel();
        labelTransaction = new javax.swing.JLabel();
        form = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        formward = new javax.swing.JScrollPane();
        tblWardList = new javax.swing.JTable();
        wardcodeUpdate = new javax.swing.JTextField();
        update = new javax.swing.JLabel();
        wardname = new javax.swing.JTextField();
        updatebutton = new javax.swing.JButton();
        delete = new javax.swing.JLabel();
        wardcodeDelete = new javax.swing.JTextField();
        deletebutton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inWardName = new javax.swing.JTextField();
        addbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnWardOccupied = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(0, 102, 204));
        header.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        header.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Hospital Management System");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(705, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labekManage.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        labekManage.setText(" Manage Ward");
        labekManage.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));

        menu.setBackground(new java.awt.Color(0, 102, 204));

        laeblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        laeblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laeblDashboard.setText("Dashboard");
        laeblDashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        laeblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laeblDashboardMouseClicked(evt);
            }
        });

        labelDoctor.setForeground(new java.awt.Color(255, 255, 255));
        labelDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDoctor.setText("Doctor");
        labelDoctor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDoctorMouseClicked(evt);
            }
        });

        labelWard.setForeground(new java.awt.Color(255, 255, 255));
        labelWard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWard.setText("Ward");
        labelWard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        labelPatient.setForeground(new java.awt.Color(255, 255, 255));
        labelPatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPatient.setText("Patient");
        labelPatient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPatientMouseClicked(evt);
            }
        });

        labelTransaction.setForeground(new java.awt.Color(255, 255, 255));
        labelTransaction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTransaction.setText("Transaction");
        labelTransaction.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTransactionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(laeblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
            .addComponent(labelWard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(laeblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWard, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        form.setBackground(new java.awt.Color(255, 255, 255));

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));

        tblWardList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ward Code", "Ward Name"
            }
        ));
        tblWardList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWardListMouseClicked(evt);
            }
        });
        formward.setViewportView(tblWardList);

        wardcodeUpdate.setText("Ward Code");
        wardcodeUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardcodeUpdateActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        update.setText("Update");

        wardname.setText("Ward Name");

        updatebutton.setBackground(new java.awt.Color(0, 102, 204));
        updatebutton.setForeground(new java.awt.Color(255, 255, 255));
        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delete.setText("Delete");

        wardcodeDelete.setText("Ward Code");
        wardcodeDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardcodeDeleteActionPerformed(evt);
            }
        });

        deletebutton.setBackground(new java.awt.Color(0, 102, 204));
        deletebutton.setForeground(new java.awt.Color(255, 255, 255));
        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Add Ward");

        jLabel11.setText("Ward Name");

        addbutton.setBackground(new java.awt.Color(0, 102, 204));
        addbutton.setForeground(new java.awt.Color(255, 255, 255));
        addbutton.setText("Add");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(formward, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wardcodeUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(wardname)
                            .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updatebutton))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deletebutton)
                            .addComponent(wardcodeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete))
                        .addGap(21, 21, 21))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(38, 38, 38)
                                .addComponent(inWardName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addbutton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update)
                            .addComponent(delete))
                        .addGap(26, 26, 26)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wardcodeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wardcodeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(wardname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updatebutton)
                            .addComponent(deletebutton)))
                    .addComponent(formward, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(inWardName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addbutton)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jButton1.setText("Ward List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnWardOccupied.setText("Ward  Occupied");
        btnWardOccupied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWardOccupiedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnWardOccupied)
                        .addGap(0, 679, Short.MAX_VALUE))
                    .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnWardOccupied))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labekManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labekManage, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wardcodeUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardcodeUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wardcodeUpdateActionPerformed

    private void wardcodeDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardcodeDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wardcodeDeleteActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        Kamar kam = new Kamar().getById(Integer.parseInt(wardcodeDelete.getText()));
        kam.delete();
        JOptionPane.showMessageDialog(this, "Data telah dihapus");
        dataToTable();
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        Kamar kam = new Kamar();
        kam.setNamaKamar(inWardName.getText());
        kam.save();
        JOptionPane.showMessageDialog(this, "Data telah ditambahkan");
        dataToTable();
    }//GEN-LAST:event_addbuttonActionPerformed

    private void laeblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laeblDashboardMouseClicked
        new AdminMenuPetugas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laeblDashboardMouseClicked

    private void labelDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDoctorMouseClicked
        new AdminMenuDokter().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelDoctorMouseClicked

    private void labelPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPatientMouseClicked
        new AdminMenuPasien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelPatientMouseClicked

    private void labelTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTransactionMouseClicked
        new AdminMenuTransaction().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelTransactionMouseClicked

    private void btnWardOccupiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWardOccupiedActionPerformed
        new AdminMenuWardOccupied().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnWardOccupiedActionPerformed

    private void tblWardListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWardListMouseClicked
        int selectedRow = tblWardList.getSelectedRow();
        wardcodeUpdate.setText(model.getValueAt(selectedRow, 0).toString());
        wardcodeDelete.setText(model.getValueAt(selectedRow, 0).toString());
        
        wardname.setText(model.getValueAt(selectedRow, 1).toString());
    }//GEN-LAST:event_tblWardListMouseClicked

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        Kamar kam = new Kamar().getById(Integer.parseInt(wardcodeUpdate.getText()));
        kam.setNamaKamar(wardname.getText());
        kam.save();
        JOptionPane.showMessageDialog(this, "Data telah terupdate");
        dataToTable();
    }//GEN-LAST:event_updatebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenuWardList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenuWardList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenuWardList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenuWardList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenuWardList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JButton btnWardOccupied;
    private javax.swing.JLabel delete;
    private javax.swing.JButton deletebutton;
    private javax.swing.JPanel form;
    private javax.swing.JPanel formPanel;
    private javax.swing.JScrollPane formward;
    private javax.swing.JPanel header;
    private javax.swing.JTextField inWardName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labekManage;
    private javax.swing.JLabel labelDoctor;
    private javax.swing.JLabel labelPatient;
    private javax.swing.JLabel labelTransaction;
    private javax.swing.JLabel labelWard;
    private javax.swing.JLabel laeblDashboard;
    private javax.swing.JPanel menu;
    private javax.swing.JTable tblWardList;
    private javax.swing.JLabel update;
    private javax.swing.JButton updatebutton;
    private javax.swing.JTextField wardcodeDelete;
    private javax.swing.JTextField wardcodeUpdate;
    private javax.swing.JTextField wardname;
    // End of variables declaration//GEN-END:variables
}
